server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/medicory
    username: medicory
    password: Medicory.1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: sameh.tarek.fci@gmail.com
    password: rlob ihjl tbxu saec
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  password-reset:
    code-length: 6
    code-expiration-minutes: 30

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
